// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: storage_message.proto

package pcbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storage_Type int32

const (
	Storage_UNKNOWN Storage_Type = 0
	Storage_SSD     Storage_Type = 1
	Storage_HDD     Storage_Type = 2
)

// Enum value maps for Storage_Type.
var (
	Storage_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "SSD",
		2: "HDD",
	}
	Storage_Type_value = map[string]int32{
		"UNKNOWN": 0,
		"SSD":     1,
		"HDD":     2,
	}
)

func (x Storage_Type) Enum() *Storage_Type {
	p := new(Storage_Type)
	*p = x
	return p
}

func (x Storage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Storage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_message_proto_enumTypes[0].Descriptor()
}

func (Storage_Type) Type() protoreflect.EnumType {
	return &file_storage_message_proto_enumTypes[0]
}

func (x Storage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Storage_Type.Descriptor instead.
func (Storage_Type) EnumDescriptor() ([]byte, []int) {
	return file_storage_message_proto_rawDescGZIP(), []int{0, 0}
}

type Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32        `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   Storage_Type `protobuf:"varint,2,opt,name=type,proto3,enum=Storage_Type" json:"type,omitempty"`
}

func (x *Storage) Reset() {
	*x = Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_storage_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_storage_message_proto_rawDescGZIP(), []int{0}
}

func (x *Storage) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Storage) GetType() Storage_Type {
	if x != nil {
		return x.Type
	}
	return Storage_UNKNOWN
}

var File_storage_message_proto protoreflect.FileDescriptor

var file_storage_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x25, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x53, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x48,
	0x44, 0x44, 0x10, 0x02, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x79, 0x72, 0x66, 0x31, 0x30, 0x35, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x61,
	0x73, 0x65, 0x2f, 0x47, 0x6f, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2f, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_storage_message_proto_rawDescOnce sync.Once
	file_storage_message_proto_rawDescData = file_storage_message_proto_rawDesc
)

func file_storage_message_proto_rawDescGZIP() []byte {
	file_storage_message_proto_rawDescOnce.Do(func() {
		file_storage_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_message_proto_rawDescData)
	})
	return file_storage_message_proto_rawDescData
}

var file_storage_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storage_message_proto_goTypes = []interface{}{
	(Storage_Type)(0), // 0: Storage.Type
	(*Storage)(nil),   // 1: Storage
}
var file_storage_message_proto_depIdxs = []int32{
	0, // 0: Storage.type:type_name -> Storage.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storage_message_proto_init() }
func file_storage_message_proto_init() {
	if File_storage_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_message_proto_goTypes,
		DependencyIndexes: file_storage_message_proto_depIdxs,
		EnumInfos:         file_storage_message_proto_enumTypes,
		MessageInfos:      file_storage_message_proto_msgTypes,
	}.Build()
	File_storage_message_proto = out.File
	file_storage_message_proto_rawDesc = nil
	file_storage_message_proto_goTypes = nil
	file_storage_message_proto_depIdxs = nil
}
